In [ ]:
import pandas as pd

train = pd.read_csv('customer_train.csv')
test = pd.read_csv('customer_test.csv')

#print(train.head(10))

#preprocessing
#null preprocessing

train['payback'] = train['payback'].fillna(0)
test['payback'] = test['payback'].fillna(0)


print(train.head(5))

from sklearn.preprocessing import LabelEncoder

#label encoding

cols = ['main_product','where']

for col in cols:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col])
    test[col] = le.fit_transform(test[col])


target = train.pop('gender')

#data split

from sklearn.model_selection import train_test_split

x_train , x_val , y_train, y_val = train_test_split(train, target, test_size = 0.2 , random_state =0)
# why zero value int land state?


# ml 

from sklearn.ensemble  import RandomForestClassifier

model = RandomForestClassifier(random_state = 0)
model.fit(x_train, y_train)


from sklearn.metrics import roc_auc_score

pred = model.predict_proba(x_val)

print(roc_auc_score(y_val, pred[:,1]))


pred = model.predict_proba(test)
submit = pd.DataFrame({'pred': pred[:,1]})
submit.to_csv('submission.csv', index = False)
print(submit.head())

   cust_id  total_buy   max_buy    payback main_product where  days  \
0        0   68282840  11264000  6860000.0           기타   강남점    19
1        1    2136000   2136000   300000.0          스포츠   잠실점     2
2        2    3197000   1639000        0.0       남성 캐주얼   관악점     2
3        3   16077620   4935000        0.0           기타   광주점    18
4        4   29050000  24000000        0.0           보석  본  점     2

   buy_per_day  weekend_come  buy_period  gender
0     3.894737      0.527027          17       0
1     1.500000      0.000000           1       0
2     2.000000      0.000000           1       1
3     2.444444      0.318182          16       1
4     1.500000      0.000000          85       0
0.6150188336494536
   pred
0  0.55
1  0.29
2  0.25
3  0.56
4  0.53

In [4]:
import pandas as pd

train = pd.read_csv('customer_train.csv')
test = pd.read_csv('customer_test.csv')

#train.info()
print(test.head(5))

#train.isnull().sum()

train['payback'] = train['payback'].fillna(0)
test['payback'] = test['payback'].fillna(0)



from sklearn.preprocessing import LabelEncoder


cols = ['main_product','where']

for col in cols:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col])
    test[col] = le.fit_transform(test[col])    

target = train.pop('gender')

from sklearn.model_selection import train_test_split

x_train, x_val ,y_train, y_val = train_test_split(train,target,test_size=0.2, random_state = 0)


from sklearn.ensemble import RandomForestClassifier


model = RandomForestClassifier()

model.fit(x_train,y_train)

from sklearn.metrics import roc_auc_score

pred = model.predict_proba(x_val)

print(roc_auc_score(y_val, pred[:,1]))


pred = model.predict_proba(test)

submit = pd.DataFrame({'pred':pred[:,1]})

submit.to_csv('submmtion.csv' , index = False)

print(submit.head(10))

   cust_id  total_buy   max_buy     payback main_product where  days  \
0     3500   70900400  22000000   4050000.0           골프  부산본점    13
1     3501  310533100  38558000  48034700.0          농산물   잠실점    90
2     3502  305264140  14825000  30521000.0         가공식품  본  점   101
3     3503    7594080   5225000         NaN         주방용품  부산본점     5
4     3504    1795790   1411200         NaN          수산품  청량리점     3

   buy_per_day  weekend_come  buy_period
0     1.461538      0.789474          26
1     2.433333      0.369863           3
2    14.623762      0.083277           3
3     2.000000      0.000000          47
4     2.666667      0.125000           8
0.6047115290430012
   pred
0  0.56
1  0.16
2  0.24
3  0.56
4  0.50
5  0.57
6  0.28
7  0.30
8  0.33
9  0.30

In [26]:
import pandas as pd


x_test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/X_test.csv")
x_train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/X_train.csv")
y_train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch2/y_train.csv")


from sklearn.preprocessing import LabelEncoder

cols = x_train.select_dtypes(include = 'object').columns


display(x_train[cols].head(3))

for col in cols:
    le = LabelEncoder()
    x_train[col] = le.fit_transform(x_train[col])
    x_test[col] = le.transform(x_test[col])

display(x_train[cols].head(3))

x_train = x_train.drop('ID', axis = 1)
x_test_id = x_test.pop('ID')

from sklearn.model_selection import train_test_split
x_train , x_val , y_train, y_val = train_test_split(x_train,y_train['Reached.on.Time_Y.N'],test_size = 0.2 , random_state =0)
x_train.shape, x_val.shape


from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state = 0)
model.fit(x_train,y_train)
pred = model.predict_proba(x_val)

from sklearn.metrics import roc_auc_score

print(roc_auc_score(y_val, pred[:,1]))

  Warehouse_block Mode_of_Shipment Product_importance Gender
0               B             Ship                low      F
1               D             Ship             medium      M
2               B             Ship             medium      F

   Warehouse_block  Mode_of_Shipment  Product_importance  Gender
0                1                 2                   1       0
1                3                 2                   2       1
2                1                 2                   2       0

0.7605499664654595

In [39]:
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch3/test.csv")


pd.options.display.float_format = '{:.4f}'.format
train.describe()

target = train.pop('TravelInsurance')
train.describe(include = 'object')
print(train.shape, test.shape)
train = pd.get_dummies(train)
test = pd.get_dummies(test)
print(train.shape, test.shape)

train.columns


from sklearn.model_selection import train_test_split

x_train, x_val , y_train , y_val = train_test_split(train, target , test_size = 0.2 , random_state =0)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state = 0)

model.fit(x_train,y_train)

pred = model.predict_proba(x_val)

from sklearn.metrics import roc_auc_score

print(roc_auc_score(y_val, pred[:,1]))

(1490, 9) (497, 9)
(1490, 13) (497, 13)
0.8506578947368421

In [51]:
import pandas as pd


train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch4/test.csv")


target = train.pop('Segmentation')

print(train.head(5))

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder
train.describe()

train = pd.get_dummies(train)
test = pd.get_dummies(test)

print(train.shape , test.shape)

from sklearn.model_selection import train_test_split

x_train , x_val , y_train, y_val = train_test_split(train, target , test_size = 0.2 , random_state = 0)

from sklearn.ensemble  import RandomForestClassifier

model = RandomForestClassifier(random_state = 0)

model.fit(x_train, y_train)

pred = model.predict(x_val)

from sklearn.metrics import f1_score

print(f1_score(y_val, pred, average='macro'))

pred = model.predict(test)

submit = pd.DataFrame({
    'ID': test['ID'],
    'Segmentation': pred
})
submit.to_csv("result.csv",index = False)

pd.read_csv("result.csv")

       ID  Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0  462809    Male           No   22        No  Healthcare           1.0000
1  466315  Female          Yes   67       Yes    Engineer           1.0000
2  461735    Male          Yes   67       Yes      Lawyer           0.0000
3  461319    Male          Yes   56        No      Artist           0.0000
4  460156    Male           No   32       Yes  Healthcare           1.0000

  Spending_Score  Family_Size  Var_1
0            Low       4.0000  Cat_4
1            Low       1.0000  Cat_6
2           High       2.0000  Cat_6
3        Average       2.0000  Cat_6
4            Low       3.0000  Cat_6
(6665, 29) (2154, 29)
0.5020137672414862

          ID  Segmentation
0     458989             2
1     458994             3
2     459000             3
3     459003             3
4     459005             1
...      ...           ...
2149  467950             4
2150  467954             4
2151  467958             2
2152  467961             2
2153  467968             4

[2154 rows x 2 columns]